services:
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./sites:/etc/nginx/sites-enabled
      - ./docs:/var/www
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6s & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
